### ISSUE TITLE
KISS not seen yet

### ISSUE THREAD

**Issue by Snake-Plissken-999** [HenryRLee/PokerHandEvaluator#11]
Guys I have to say: good ideas on how approach the hand ranking problem, but then you lose the audience in the build phase: I mean is good to have unit tests built automatically using googletest, but by any chance we will have a clear idea on how to have something that works? libpheval is yet to be seen declared anywhere...

So this is a general issue on clarity as there are missing instructions on:
1) assemble the code without manual intervention (even using CMake I need to adjust the folders manually);
2) generate any solution, i.e.  a .dll or at least tell the uninitiated how to create/see the "ghost library" libpheval...

Cool stuff tough, would be good to be able to use it :)

**Comment by HenryRLee** [comment]
Hi @Snake-Plissken-999, you're right. When I moved from Makefile to CMake, I lost the build command for the `libpheval`, simply because I am not good at CMake at this moment. I will find some time to fix this. Or, if you are interested, you can create a PR for a command building the library and add the instructions in the README file.

When I were exploring other open source projects, I saw many of them are using the `mkdir build; cd build; cmake ..` way, which I thought it was something conventional. I believe at the moment, we can still do `cmake .` in the `cpp` folder directly. But which building option should we recommend (documented in README), is open for discussion. In addition, I am planning to add a Makefile back to the repo so that user can build without running CMake.

Thank you for advice. These are very good contributions. Still, if you can create PR to improve it, it would be very much appreciated.

**Comment by Snake-Plissken-999** [comment]
Hi Henry, thanks for your answer, I would like to help but I am not an expert in CMake, I just learnt how to use it last week to compile your code. I can however tell you how I proceeded so far: CMake to build the project, then uploaded the project on VS, and from there I built pheval.dll and unit_tests.exe as 2 standalone (I just needed the .dll for Python Ctypes). I struggled with phevaluator, which is not called/linked in the CMake process, so I tried to compile it manually in VS but my C++ skills are too low for that... so for now I'll use the pheval.dll :)
