### ISSUE TITLE
No makefile found after running cmake

### ISSUE THREAD

**Issue by tryabin** [HenryRLee/PokerHandEvaluator#13]
I tried to build the C++ library according to the README in the "cpp" directory, and got an error when I tried to run the "make" step because no makefile was found. Is a makefile supposed to be generated by the "cmake" step, or maybe the makefile was not committed?

**Comment by HenryRLee** [comment]
Yes, currently CMake is required, running `cmake` will generate a Makefile according to your OS. But I am planning to add a Makefile for general Linux/MacOS systems very soon.

**Comment by tryabin** [comment]
In my case the `cmake ..` command seems to complete successfully, since I don't see any `CMakeError.log` file in the `cpp\build\CMakeFiles` directory , but I don't see a Makefile in the `cpp\build` directory.

**Comment by HenryRLee** [comment]
Are you using Windows environment to build the library? I don't have any experience in that. Might need community support for this.

If you are more comfortable in Makefile, I just added a Makefile in the cpp directory, which builds the library only. But that does not include the unit test, because google test requires CMake to build.

Also inside the `examples` directory you may find some source code along with a Makefile as well.

Just checkout the latest code from master branch you may find it.

**Comment by HenryRLee** [comment]
Or, if you are using Windows with Visual Studio or Visual Studio Code, I found these documentation may be helpful:
https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019
https://vector-of-bool.github.io/docs/vscode-cmake-tools/index.html

**Comment by tryabin** [comment]
I am using Windows with Cygwin. I was able to successfully build the library in Cygwin using the new Makefile, and was then able to successfully build the examples and run them.
