### ISSUE TITLE
8+ cards algorithms doesn't consider the difference between pockets and board cards

### ISSUE THREAD

**Issue by AndrewPlakhotnyi** [HenryRLee/PokerHandEvaluator#17]
There is no poker game where we should choose the best 5 among 8 or 9 cards regardless of how many pocket cards participate in the final hand. 

Omaha requires exactly two pocket cards to be present in the final hand.

Just saying :D

**Comment by HenryRLee** [comment]
Thank you! I wasn't awared of that. That's something worth thinking about.

**Comment by HenryRLee** [comment]
Now I have a solution in mind, using the same Perfect Hash algorithm to evaluate Omaha poker hands. It might take around one week to code it and generate the hash tables. We'll see the performance by then.

**Comment by HenryRLee** [comment]
I coded the Omaha evaluator and passed all the tests. The time performance is about 10% slower than the original 9-card evaluator, and no more than 1x slower than the 5-card evaluator. Considering its complexity, I think it is still pretty good.

But I am still improving the benchmark, as I found out even my 5-card evaluator has been slowed down.

In the meantime, I am deprecating the 8-card and 9-card evaluators in the near future, since you pointed out that nobody actually uses them.
