### ISSUE TITLE
dptables.c suits

### ISSUE THREAD

**Issue by djong0** [HenryRLee/PokerHandEvaluator#70]
Hi @HenryRLee,  I'm trying to generate the array of suits[4609],  then I got a different value  of suits[520]. 
"dptables.c" suits[520] is 3, I got 1.
Is there something wrong？

**Comment by HenryRLee** [comment]
Hi @djong0, it's a good question!

Actually, we should never come to `suits[520]`, not if we are evaluating 5, 6, or 7 cards. Because, 520 is the sum of 0x8 and 0x200, so it should only consist of two cards.

I assume you're generating this table using 9 cards, with 8 cards in suit 0x1, and 1 card in suit 0x200. In that case, 8 * 0x1 is also 0x8, so it has the same value with 520. This is actually an overflow issue, because we only allocated 3 bits for each suit, so we should only have 8 different states in each suit, which can represent 0 to 7 cards.

Now, you can see, in my table, I had the value 3 for `suits[520]`. This is also a bug when I was trying to support 9-card evaluation. I believe in that time, I had 8 cards in suit 0x40, and 1 card in 0x8. Although I deprecated 9-card hand evaluation later, the value in the table still remained.

**Comment by djong0** [comment]
Yes,  you are right,  I'm generating this table using 9 cards. Now I understand why `evaluate_9cards` function not use `suits[4609]`.
Thank you for your reply.
