### ISSUE TITLE
Exactly 2 hole cards not considered in Omaha

### ISSUE THREAD

**Issue by ykcodebook** [HenryRLee/PokerHandEvaluator#81]
I tried to evaluate a hand for omaha and this is my hand used.

`p3 = evaluate_omaha_cards("3s", "5h", "Qs", "Qd", "9h", "Ks", "8c", "Js", "5c")`

This results with ranking of 2788 which is Two Pair (Qs Qd 5h 5c) which is wrong since only one card from the hole is considered for the evaluation.

Any solution for this?

**Comment by HenryRLee** [comment]
Hi @ykcodebook , the evaluation is correct.

The final made hands should be "Qs", "Qd", "5h", "5c", "Ks". It's picking exactly three cards from the community cards and two cards from the hole cards.

**Comment by azriel1rf** [comment]
@ykcodebook @HenryRLee 
I've revisited this scenario to confirm, and it appears to be expected behavior.

Community cards: "3s", <ins>"5h"</ins>, <ins>"Qs"</ins>, <ins>"Qd"</ins>, "9h"
Hole cards: <ins>"Ks"</ins>, "8c", "Js", <ins>"5c"</ins>

Selected hand: "Qs", "Qd", "5h", "5c", "Ks"

```Python
from phevaluator import evaluate_omaha_cards, evaluate_cards

print(evaluate_omaha_cards("3s", "5h", "Qs", "Qd", "9h", "Ks", "8c", "Js", "5c"))  # 2788
print(evaluate_cards("Qs", "Qd", "5h", "5c", "Ks"))  # 2788
```

Here, both `evaluate_omaha_cards` and `evaluate_cards` functions return 2788, confirming that the evaluation is consistent and adheres to the rules of Omaha poker.

**Comment by ykcodebook** [comment]
Thanks! I may have misunderstood the rule of omaha. Appreciate the quick reply.
